// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvEEUiKLeodNPS5ZCnYviVDHU-Kn3gMBY',
    appId: '1:1018082712087:web:7739eb38aeb46c940cda52',
    messagingSenderId: '1018082712087',
    projectId: 'placer-io',
    authDomain: 'placer-io.firebaseapp.com',
    storageBucket: 'placer-io.appspot.com',
    measurementId: 'G-5NYSJ6C9NB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYIr8W8GayQ8rWNsHd-YwUQWyfBYNsNhQ',
    appId: '1:1018082712087:android:51342d361b1c87d10cda52',
    messagingSenderId: '1018082712087',
    projectId: 'placer-io',
    storageBucket: 'placer-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFSC4eJwk13RvByKBElhScNMWyiYcWtQs',
    appId: '1:1018082712087:ios:2b7c2c37e6b53ca60cda52',
    messagingSenderId: '1018082712087',
    projectId: 'placer-io',
    storageBucket: 'placer-io.appspot.com',
    iosClientId: '1018082712087-b0v6ehqq9a2q8f3noa290vihs4igd6p9.apps.googleusercontent.com',
    iosBundleId: 'com.placer.placer',
  );
}
